### ISSUE TITLE
FreeOTP client for the desktop

### ISSUE THREAD

**Issue by dustymabe** [freeotp/freeotp.github.io#1] opened 2017-03-06 00:58 UTC
Is there a FreeOTP client for the desktop (i think i've seen some before that are plugins for your web browswer) that could be used? I use FreeOTP on my phone, but worry if I were to lose my phone I'd have to deal with backup codes and/or support departments for my accounts that I have 2FA turned on for. This may be a really bad idea so let me know of all the reasons I should not do this :) 

I notice another hatter has written a [web app](https://github.com/gbraad/gauth) that does OTP. I would be interested to know if the authors of FreeOTP would recommend using that or to go some other route.

Thanks!

**Comment by dustymabe** [comment] 2017-03-06 01:01
There is also [bash-otp](https://github.com/poolpog/bash-otp) for running from the command line, but not sure about how good (or bad) it is.

**Comment by dustymabe** [comment] 2017-03-06 02:39
just realized I opened this against the "website code", oh well I guess it will still serve the purpose of getting the question answered. Sorry about that.

**Comment by npmccallum** [comment] 2017-03-06 15:12
I am both strongly in favor of a desktop client and strongly against existing implementations.

A proper implementation would use the TPM to ensure the key cannot be compromised. TPM 2.0 supports HMAC, so we are just waiting for the platform support to mature at this point.

**Comment by dustymabe** [comment] 2017-03-06 15:15
so would it be safe to say that you are planning a FreeOTP desktop client at some point? How far off do you think it will be before `platform support` to be mature enough?

**Comment by npmccallum** [comment] 2017-03-06 15:38
Yes. Intel first needs to land the TPM 2.0 resource manager in the kernel. It looks like they will miss 4.11.

One this is landed, we need an implementation of the TSS library. AFAICS, this still needs to be built on top of the TSS SYS library, which is partially implemented already. I may write directly to the SYS API if I'm too impatient. :)

**Comment by dustymabe** [comment] 2017-03-06 17:02
cool - can I use this ticket as a tracker for that work and status updates? The other options are we close this ticket and there are no status updates, or I open the ticket in a more appropriate location and follow updates there. 

Thanks again.

**Comment by npmccallum** [comment] 2017-03-06 18:00
I'm fine with keeping this open until there is progress.

**Comment by diev** [comment] 2017-12-04 12:59
I will subscribe too.

**Comment by juancarlospaco** [comment] 2017-12-17 06:53
I am also interested on FreeOTP Desktop.

**Comment by termlen0** [comment] 2018-05-10 14:54
+1

**Comment by zekaguilar** [comment] 2018-05-31 01:36
+1

**Comment by ericwmc** [comment] 2018-05-31 01:57
+1 thanks

**Comment by morgancoxuk** [comment] 2018-06-19 11:54
i am also interested in otp linux desktop client

**Comment by PhilippVerpoort** [comment] 2018-06-30 13:52
+1

**Comment by Frontrider** [comment] 2018-07-23 08:12
Interested in it.

**Comment by MHappersberger** [comment] 2018-09-17 07:40
+1

**Comment by yummuy** [comment] 2018-09-21 09:02
+1

**Comment by billpapadimas** [comment] 2019-03-02 15:31
+1

**Comment by itcrowdsource** [comment] 2019-03-02 19:56
https://chrome.google.com/webstore/detail/authenticator/bhghoamapcdpbohphigoooaddinpkbai?hl=en

**Comment by ralcon** [comment] 2019-03-12 18:21
+1

**Comment by diraol** [comment] 2019-03-12 18:47
Just to share with everyone, I've been using KeePass with KeePassXC Desktop Client to manage both passwords and TOTP for the past few months without issues, it has been working very nicely to me.
I'm able to sync/share my database across devices (notebooks, cellphone, etc) and it works pretty well everywhere!

Obs: On my Mobile Phone I'm using Keepass2Android APP.

**Comment by LizaDarrous** [comment] 2020-03-05 09:16
Bump, super interested!

**Comment by jemag** [comment] 2020-11-23 17:01
Given that the issue is now more than 3 years old and there were plans to create a desktop application at the time. Would it be possible to provide an update? 

e.g.:
Is still this in the plans?
If so, is it currently being worked on?

**Comment by morgancoxuk** [comment] 2020-11-24 20:29
For last few years I have been using this app on Linux, its really good

https://github.com/paolostivanin/OTPClient

There are repos for ubuntu, debian ,etc (and its in AUR for arch)

**Comment by iholder101** [comment] 2023-02-06 15:01
+1

This is now almost 6 years old.
Can someone please share an update?

**Closed** 2023-08-07 14:24 UTC

**Comment by iholder101** [comment] 2023-08-07 14:29
@justin-stephenson Can you explain why this is closed?

**Comment by s-b-repo** [comment] 2024-02-26 20:01
please can we get a desktop client

**Comment by sohzm** [comment] 2025-02-06 06:15
requesting desktop client (its 2025)
